version: "3"

services:
  minio:
    image: minio/minio
    container_name: minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - MINIO_DOMAIN=minio
    volumes:
      - ./data/minio-data:/data
    networks:
      datalake_net:
        aliases:
          - warehouse.minio
    ports:
      - 9001:9001
      - 9000:9000
    command: ["server", "/data", "--console-address", ":9001"]
  mc:
    depends_on:
      - minio
    image: minio/mc
    container_name: mc
    networks:
      datalake_net:
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add minio http://minio:9000 admin password) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc rm -r --force minio/warehouse;
      /usr/bin/mc mb minio/warehouse;
      /usr/bin/mc policy set public minio/warehouse;
      tail -f /dev/null
      "
  postgres:
    image: postgres:16
    container_name: postgres
    volumes:
      - ./data/pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'hive'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'metastore_db'
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    ports:
      - '5432:5432'
    networks:
      datalake_net:
  metastore-standalone:
    image: apache/hive:3.1.3
    container_name: metastore-standalone
    volumes:
      - ./conf/hive:/hive_custom_conf
    networks:
      datalake_net:
    environment:
      HIVE_CUSTOM_CONF_DIR: '/hive_custom_conf'
      SERVICE_NAME: 'metastore'
      HADOOP_CLASSPATH: '/opt/hadoop/share/hadoop/tools/lib/aws-java-sdk-bundle-1.11.271.jar:/opt/hadoop/share/hadoop/tools/lib/hadoop-aws-3.1.0.jar'
      DB_DRIVER: 'postgres'
      SERVICE_OPTS: '-Xmx1G -Djavax.jdo.option.ConnectionDriverName=org.postgresql.Driver
                     -Djavax.jdo.option.ConnectionURL=jdbc:postgresql://postgres:5432/metastore_db
                     -Djavax.jdo.option.ConnectionUserName=hive
                     -Djavax.jdo.option.ConnectionPassword=password'
      IS_RESUME: 'false'
    ports:
      - 9083:9083
    depends_on:
      - minio
      - postgres
  trino:
    image: trinodb/trino
    container_name: trino
    volumes:
      - ./conf/trino:/etc/trino
    networks:
      datalake_net:
    ports:
      - 8080:8080
    depends_on:
      - metastore-standalone
networks:
  datalake_net: