services:
  rustfs:
    image: rustfs/rustfs:1.0.0-alpha.90
    container_name: rustfs
    user: "0:0"
    environment:
      - RUSTFS_ACCESS_KEY=admin
      - RUSTFS_SECRET_KEY=password
      - RUSTFS_ADDRESS=0.0.0.0:9000
      - RUSTFS_CONSOLE_ADDRESS=0.0.0.0:9001
      - RUSTFS_CONSOLE_ENABLE=true
      - RUSTFS_VOLUMES=/data
    volumes:
      - ./data/rustfs-data:/data
      - ./data/rustfs-logs:/logs
    networks:
      datalake_net:
        aliases:
          - warehouse.rustfs
    ports:
      - 9001:9001
      - 9000:9000
  mc:
    depends_on:
      - rustfs
    image: minio/mc:RELEASE.2025-08-13T08-35-41Z
    container_name: mc
    networks:
      datalake_net:
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
    entrypoint: |
      /bin/sh -c "
      until (/usr/bin/mc alias set rustfs http://rustfs:9000 admin password) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc mb -p rustfs/warehouse;
      /usr/bin/mc policy set public rustfs/warehouse;
      tail -f /dev/null
      "
  postgres:
    image: postgres:16
    container_name: postgres
    volumes:
      - ./data/pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'hive'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'metastore_db'
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hive -d metastore_db"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      datalake_net:
  metastore-standalone:
    image: apache/hive:4.2.0
    container_name: metastore-standalone
    entrypoint:
      - /bin/bash
      - /hive-entrypoint.sh
    volumes:
      - ./conf/hive/hive-site.xml:/hive_custom_conf/hive-site.xml:ro
      - ./docker/hive-entrypoint.sh:/hive-entrypoint.sh:ro
      - ./postgresql-42.7.3.jar:/opt/hive/lib/postgresql-42.7.3.jar
    networks:
      datalake_net:
    environment:
      SERVICE_NAME: 'metastore'
      DB_DRIVER: 'postgres'
      HADOOP_CLASSPATH: '/opt/hadoop/share/hadoop/tools/lib/bundle-2.24.6.jar:/opt/hadoop/share/hadoop/tools/lib/hadoop-aws-3.4.1.jar'
      SERVICE_OPTS: '-Djavax.jdo.option.ConnectionDriverName=org.postgresql.Driver -Djavax.jdo.option.ConnectionURL=jdbc:postgresql://postgres:5432/metastore_db -Djavax.jdo.option.ConnectionUserName=hive -Djavax.jdo.option.ConnectionPassword=password'
      HIVE_CUSTOM_HIVE_SITE: '/hive_custom_conf/hive-site.xml'
    ports:
      - 9083:9083
    depends_on:
      postgres:
          condition: service_healthy
  trino:
    image: trinodb/trino:480
    container_name: trino
    volumes:
      - ./conf/trino:/etc/trino
    networks:
      datalake_net:
    ports:
      - 8080:8080
networks:
  datalake_net:
