connector.name=lakehouse
lakehouse.table-type=HIVE

hive.metastore.uri=thrift://metastore-standalone:9083
hive.non-managed-table-writes-enabled=true
hive.storage-format=PARQUET
hive.compression-codec=zstd

delta.unique-table-location=false

fs.native-s3.enabled=true
s3.region=us-east-1
s3.endpoint=http://rustfs:9000/
s3.aws-access-key=admin
s3.aws-secret-key=password
s3.path-style-access=true

